use_frameworks!

platform :ios, '10.0'

target 'SBAIPractice_Example' do
  pod 'SBAIPractice', :path => '../'

  target 'SBAIPractice_Tests' do
    inherit! :search_paths

    
  end
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
